version: '3.7'

#volumes:
#    prometheus_data: {}
#    grafana_data: {}

#networks:
#  front-tier:
#  rabbitmq-prometheus:

services:
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
        #- /cgroup:/cgroup:ro  
    ports:
      - 8080:8080
    restart: always

#  mongo_exporter:
#    restart: 'always'
#    command:
#      - '--mongodb.uri=mongodb://root:rootpassword@mongodb:27017/admin'
#      - '--collect.database'
#      - '--collect.collection'
#      - '--collect.topmetrics'
#      - '--collect.indexusage'
#      - '--collect.connpoolstats'
#    networks:
#      - skan-net      
#    ports:
#      - '9216:9216'
#    image: mongodb_exporter:latest
#    container_name: mongo-exporter


networks:
  skan-net:
    external: true
